name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  haxelib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: mxhx-resolver-haxelib
          path: |
            src/
            haxelib.json
            README.md
            LICENSE
            NOTICE
            CHANGELOG.md
          if-no-files-found: error
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - name: Set up Haxelib dependencies
        run: |
          haxelib install dox --quiet
          haxelib git mxhx-parser https://github.com/mxhx-dev/mxhx-parser.git --quiet
          haxelib git mxhx-symbols https://github.com/mxhx-dev/mxhx-symbols.git --quiet
          haxelib git mxhx-manifest https://github.com/mxhx-dev/mxhx-manifest.git --quiet
          haxelib dev mxhx-resolver $GITHUB_WORKSPACE
      - name: Build API reference
        working-directory: docs
        run: haxe docs.hxml
      - uses: actions/upload-artifact@v4
        with:
          name: mxhx-resolver-docs
          path: bin/api/
          if-no-files-found: error
