name: Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cedx/setup-hashlink@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install utest --quiet
          haxelib install hxcpp --quiet
          haxelib git mxhx-parser https://github.com/mxhx-dev/mxhx-parser.git --quiet
          haxelib git mxhx-symbols https://github.com/mxhx-dev/mxhx-symbols.git --quiet
          haxelib dev mxhx-resolver $GITHUB_WORKSPACE
      - name: Run Interpreter Tests
        working-directory: test
        run: haxe test.hxml --interp
      - name: Run Neko Tests
        working-directory: test
        run: |
          haxe test.hxml --neko bin/test.n
          neko bin/test.n
      - name: Run HashLink Tests
        working-directory: test
        run: |
          haxe test.hxml --hl bin/test.hl
          hl bin/test.hl
      - name: Run Node Tests
        working-directory: test
        run: |
          haxe test.hxml --js bin/test.js
          node bin/test.js
      - name: Run C++ Tests
        working-directory: test
        run: |
          haxe test.hxml --cpp bin/test
          bin/test/Main
